### ISSUE TITLE
Wrong calculate (2+2)*2-4-4

### ISSUE THREAD

**Issue by darkfriend** [phplrt/phplrt.org#1]
### Description

Wrong calculate (2+2)*2-4-4

![image](https://user-images.githubusercontent.com/7825114/213890400-567dca0a-af38-446d-9ddd-4da0506e55f0.png)

**Comment by SerafimArts** [comment]
Whoops `¯\_(ツ)_/¯`

**Comment by SerafimArts** [comment]
Done https://github.com/phplrt/phplrt.org/commit/950f192c8ca3b5cbe982e06074860c17369c302c#diff-16d4bcd66516321eba10413c8bc85d9be9ae5e1e06c38239ec320eb9588ea46e
